# tomcat
server:
  port: 9000
spring:
  application:
    name: sk-gen-code
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/h-ui.admin-bgtemp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      url: jdbc:mysql://127.0.0.1:3306/h-ui.admin-bgtemp?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
beetl:
  templatesPath: templates/beetl/